### ISSUE TITLE
US8 - Delete Functionality

### ISSUE THREAD

**Issue by uwebury** [uwebury/trip-trove#11]
## Value proposition
As a user
I want to delete stored trips
In order to keep the app updated (i.e. when trip is done or canceled) 
## Description
![US8 - Delete Button](https://github.com/uwebury/trip-trove/assets/149960642/0c297784-a823-4779-8c57-9abde7b46a9b)
## Acceptance criteria 
- [x] Details Page: Delete button displayed on Details card, on button click alert message opens
- [x] Alert message as safety catch: „Are you sure you want to delete your trip? (Cancel / OK)
- [x] Delete Alert Message: "Are you sure you want to delete your trip?" -> Ok: deletes trip, alert disappears -> homepage with changes is displayed 
- [x] Delete Alert Message: "Are you sure you want to delete your trip?" -> Cancel: cancels deletion, alert disappears -> Details page with original data is displayed
## Tasks
- [x] Create handleDelete(event) function 
- [x] Create Delete Button on Details Page
- [x] Implement handleDelete function to Delete button (onSubmit = {handleDelete})
- [x] Implement Alert functionality

**Comment by markusgemeinder** [comment]
## Value proposition
As a user
I want to delete stored trips
In order to keep the app updated (i.e. when trip is done or canceled) 
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria 
- [ ] Details Page: delete button displayed on detail card, on button click toaster message opens
- [ ] Toaster message as safety catch: „Are you sure to delete the saved trip? (Cancel / OK)
## Tasks
- [ ] Create handleDelete(event) function 
- [ ] Create Delete Button on Details Page
- [ ] …

**Comment by MaikBerdelmann** [comment]
Looks good to me. Well done 🤙
