### ISSUE TITLE
US10 - Header and Navigation

### ISSUE THREAD

**Issue by markusgemeinder** [uwebury/trip-trove#17]
## Value proposition
As a User when I am on one of the pages
I want to see navigation icons 
So I can navigate wherever I want
## Description
![US10 - Header and Navigation](https://github.com/uwebury/trip-trove/assets/149960642/b2663375-4007-4c3a-beff-725a45e5c43c)
## Acceptance criteria
- [ ] I can see fixed Header area with page title and Logo on every page
- [ ] Logo is linked (on click back to Homepage)   
- [ ] I can see fixed Navigation bar with clickable icons at bottom of every page and on Details Page navigation icon back button "<--" additionally (not positioned inside Navigation bar)
- [ ] Header and Navigation bar are at the top level, the main content is displayed between them and "disappears" behind Header and Navigation bar when scrolling
- [ ] Home Page: home icon is highlighted (active page) 
- [ ] Create Page : “+” icon is highlighted (active page)
- [ ] Details page: no icon is highlighted, additional "<--" button (back to Home Page)
- [ ] All Navigation icons change style on hovering
- [ ] The "Page Up" navigation button is visible when scrolling down (if main content requires scrolling)
## Tasks
- [ ] Create fixed Header area
- [ ] Create fixed Navigation bar (bottom)
- [ ] Add icons to Navigation bar and link to pages
- [ ] Add :active and :hover effect to icons in Navigation bar
- [ ] Adapt position of back button "<--"
- [ ] Create Page Up button, add functionality
- [ ] Add :hover effect to all buttons

**Comment by marcbendixen** [comment]
This is a helpful UX improvement 🚀
