### ISSUE TITLE
US11 - Enhanced Packing List Management

### ISSUE THREAD

**Issue by markusgemeinder** [uwebury/trip-trove#18]
## Value proposition
As a user on the Create or Edit Form page,
I want to add items to the packing list, interact with it efficiently, and see it displayed on the Details Page,
So that I can manage my packing list effectively and view it in a structured format.

## Description
![US11 - Enhanced Packing List Management](https://github.com/uwebury/trip-trove/assets/149960642/7fd3f719-afc0-44d8-9067-ae300f2a786b)

## Acceptance criteria
- [x] After an item is added, a new empty input field with a [+] button appears.
- [x] The [+] button beside the last entry changes to an [x] (delete) button.
- [x] Clicking the [x] button deletes the item without an alert.
- [x] Clicking the [+] button with an empty input field should not add a new item.
- [x] Saving the form with packing list entries should display them as a structured list on the Details Page.

## Tasks
- [x] Change the data type of the packing list in the backend from String to Array.
- [x] Adapt the MongoDB schema and the Mongoose model for the new data structure.
- [x] Adapt the front-end and back-end components to handle the new data structure.
- [x] Adjust the front-end PackingList component to work with the new data structure.
- [x] Create the Packing List Container (input field + buttons) on the create/edit form.
- [x] Implement an input field for the packing list with a [+] button for adding items.
- [x] Allow entering new items by pressing enter or clicking the [+] button.
- [x] Implement the functionality for adding items with the [+] button.
- [x] Prevent adding empty items with the [+] button.
- [x] Implement the delete functionality with the [x] button.
- [x] Implement functionality to display the packing list on the Details Page.

**Comment by marcbendixen** [comment]
A lot of details, clean and helpful illustration, lgtm 👍

**Comment by kristinwegener** [comment]
Hi @uwebury, very nice and detailed, just one idea: the first two acceptance criteria and the last two sound more like a task, they're not described from a user perspective but from a developer perspective. Maybe you can move them to tasks or change the wording a little bit.

**Comment by uwebury** [comment]
Hi @kristinwegener, Thank you for reviewing. Your suggestion makes sense. I updated tasks accordingly and will re-post the US in a moment.
