### ISSUE TITLE
US7 - Edit Functionality

### ISSUE THREAD

**Issue by uwebury** [uwebury/trip-trove#2]
## Value proposition
As a user
I want to edit stored trip data
In order to change existing or add new information 
## Description
![US7 - Edit Button](https://github.com/uwebury/trip-trove/assets/149960642/282e53c6-8a88-4e68-9b63-9ff51a9267f9)
## Acceptance criteria 
- [x] Details Page: Edit Button displayed on detail card, on button click edit form opens
- [x] Edit form: all stored trip data displayed in form fields (Cancel Button instead of Reset Button) 
- [x] Edit form -> Cancel Button: displays alert message
- [x] Cancel Alert Message: "are you sure to discard all changes without saving?" -> Ok: discards changes, alert disappears -> edit form with original data is displayed
- [x] Cancel Alert Message: "are you sure to discard all changes without saving?" -> Cancel: alert disappears -> edit form with changed but not yet saved data is displayed
- [x] Edit form -> Save button: displays alert whether changed data shall be saved or discarded
- [x] Save Alert Message: "are you sure to save changes?" -> Ok: saves changes, alert disappears -> edit form with changed and saved data is displayed
- [x] Save Alert Message:"are you sure to save changes?" -> Cancel: discards changes, alert disappears -> edit form with changed but not yet saved data is displayed

## Tasks
- [x] Create handleEdit(event) function (PATCH method)
- [x] Create Edit Button on Details Page
- [x] Implement handleEdit function to Edit Button (onSubmit = {handleEdit})
- [x] Implement both Alert functionalities
