### ISSUE TITLE
DS - Code refactoring Form/Edit/Create Pages

### ISSUE THREAD

**Issue by markusgemeinder** [uwebury/trip-trove#24]
## Value proposition
As a developer
I want to follow the principles SoC (Separation of Concerns), Modularity and Encapsulation
In order to always have understandable and modifiable code
## Description
Currently too much nesting and dependencies, unnecessary props, ambiguous variable names and no separation of concerns in Form component, /pages/create/index.js and /pages/trips/[id]/edit.js 

## Tasks
- [ ] Gather all handle functions inside Form component, unify and clearify functions:
- [ ] Refactor and rename handleEditSave() and handleCreateSave() to handleSubmit()
- [ ] Relocate handleSubmit (handleEditSave) code fragments from edit.js to Form component 
- [ ] More efficient use of props: eliminate the prop "onToastToggle" and instead manage all functionality with only one (already existing) prop "isDisabled"
- [ ] Gather all toast message management inside Form component (except "successfully saved" which has to remain in edit.js and create/index.js)
- [ ] /lib/utils/index.js: relocate toast.error from here to Form component
- [ ] Add toast messages for use cases, which are not covered yet 
- [ ] Unify tone/voice/grammar of all toast messages

**Comment by Roland-Hufnagel** [comment]
Good idea to keep the code clean 👍
