### ISSUE TITLE
Enhancing Mobile User Experience

### ISSUE THREAD

**Issue by uwebury** [uwebury/trip-trove#27]
## Value proposition
As a mobile app user ([using iPhone SE with 375x667px as a guideline](using iPhone SE with 375x667px as a guideline)),
I want an optimized mobile experience for journey planning and packing list management,
So I can easily plan my trips and organize packing lists while on the go.

## Acceptance Criteria
- [ ] Headlines stay within header element.
- [ ] Buttons are visible on screen.
- [ ] Buttons do not overlap one another.

## Tasks
- [ ] Conduct a mobile usability analysis of all pages.
- [ ] Change font size of headlines.
- [ ] Packing list --> [while developing US11 - Enhanced Packing List Management](https://github.com/uwebury/trip-trove/issues/18)
