### ISSUE TITLE
US - Sort Function

### ISSUE THREAD

**Issue by FelixJentsch** [uwebury/trip-trove#28]
## Value proposition
As a user on the start page,
I want to be able to sort my trips,
So that I can get an better overview of my journeys.

## Description
 On the landing page there will be a sort buttons

## Acceptance criteria

- [ ] On the landing page, there should be a method to sort with the following options:

  - [ ] Nearest Date (Ascending)
  - [ ] Farthest Date (Descending)
  - [ ] Trip duration (Ascending)
  - [ ] Trip duration (Descending)
  - [ ] Alphabetical by Destination (Ascending)
  - [ ] Alphabetical by Destination (Descending)

- [ ] Initially the trips should be sorted so that the last added trip is displayed first (default)

- [ ] When I select any of the sorting options from the dropdown menu, the trips should be rearranged accordingly, and the selected sorting option should be applied instantly without requiring a page reload.

## Tasks
- [x] Add a sorting dropdown menu to the landing page.
- [x] Implement sorting functions for each of the criteria (nearest date, farthest date, trip duration).
- [x] Implement a reset function to revert to the default sorting order.
- [x] Connect the sorting and reset functions to the dropdown menu.
