### ISSUE TITLE
US - Packing List Presets (Templates / Categories)

### ISSUE THREAD

**Issue by uwebury** [uwebury/trip-trove#29]
## Value proposition
As a user when I am on the Create/Edit Page
I want to have the possibility of choosing packing list presets 
In order to get proposals for different trip scenarios
## Description
![US - Packing List Presets (Templates / Categories)](https://github.com/uwebury/trip-trove/assets/149960642/0a4ae4b3-0f77-4ab4-9838-80a6546f333f)
## Acceptance criteria
- [x] Edit/Create Page: below the label "Packing List" there is a dropdown list "Presets" (default "please select preset")  
- [x] As soon as a preset is selected all items of the preset will be displayed in the form
- [x] If I want to, I can add items to the preset or also delete items (which will be saved in the preset for the next time)
- [x] Details Page: below the title "Packing List" I see the name of the preset and the items of the selected preset
## Tasks
- [x] Create new MongoDB document with Presets
- [x] Create new mongoose schema "Presets"
- [x] Implement to API
- [x] Create component "PackingListPresets"
- [x] Adapt Form component
- [x] Adapt Details Card component (displayed on /pages/trips/[id]/index.js)
