### ISSUE TITLE
US1 - Create Homepage

### ISSUE THREAD

**Issue by markusgemeinder** [uwebury/trip-trove#3]
## Value proposition
As a user when I visit the homepage
I want to see all trips
So I can scroll through the cards

## Description
![Travel App US1](https://github.com/uwebury/trip-trove/assets/149960642/d090dcea-8ce9-4c60-a7e5-300c10380387)

## Acceptance criteria
- [x] All cards are rendered
- [x] Card contains destination, start + end date, image
- [x] Card list scrolls vertically

## Tasks
- [x] Create JSON sample array
- [x] Map the list from the array
- [x] Create Card Component
- [x] Create CardList component

**Comment by CJAkkuec** [comment]
> As a user when opening the app
> I want to see all of my trips
> So I can get an overview of them.

Good job so far! The ellipses (...) need not be part of the actual user story despite being part of the template. :)
I'd advise against "upcoming" to be part of the value proposition, because there's no current business logic being implemented that will sort the trips or prevent a past trip from being added.

The Acceptance Criteria may also include a mention of "all cards are rendered", for example.

I'd also suggest to change "create simple html" to "create Card Component" and "create CardList" component, etc.
