### ISSUE TITLE
US - Timestamp „X days until start“

### ISSUE THREAD

**Issue by Aikaakymbaeva** [uwebury/trip-trove#31]
## Value proposition
As a user
I want to see the number of days left until the start of the journey,
So that I can plan and build anticipation for the upcoming journey.
## Description
![US - Timestamp „X days until start“](https://github.com/uwebury/trip-trove/assets/92786779/126cc5c7-b8d3-4365-9e03-d6e13d40ba2f)
## Acceptance criteria
- [ ] next upcoming trips are displayed on the homepage depending on the date
- [ ] number of days is displayed highlighted
- [ ] start and end date is replaced with "scheduled"
## Tasks
- [ ] fix an icon which contains number of days and date on trips
- [ ] scheduled trips are sorted by day
- [ ]
