### ISSUE TITLE
US - Authentication (next/auth)

### ISSUE THREAD

**Issue by Aikaakymbaeva** [uwebury/trip-trove#32]
## Value proposition
As a user
I want to be able to log in to the website,
So that I have access to all the functions of the app
## Description
![US - Authentication (next/auth)
]()
## Acceptance criteria
- [ ] Display Login Button on top right
- [ ] Display Greeting on top with user name
- [ ] for users who are not logged in, do not allow to change data
- [ ] after log in, display user added trips and allow to change trips
## Tasks
- [ ] Register O-Auth-App at github
- [ ] Basic Setup
- [ ] Save frontend
- [ ] Save backend
- [ ] Personalize the data
