### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by Aikaakymbaeva** [uwebury/trip-trove#33]
## Value proposition
As a user when I am on Homepage
I want to find trips
So that I can see trips which I need
## Description
![US - Search Function]()
## Acceptance criteria
- [ ] display search input field on homepage top
- [ ] display search icon on the right to search input
- [ ] search trip by clicking enter or button
- [ ] focus search field
## Tasks
- [ ]
