### ISSUE TITLE
US2 - Create page

### ISSUE THREAD

**Issue by markusgemeinder** [uwebury/trip-trove#5]
## Value proposition
As a user when I visit the create page 
I want to enter a new trip
So I can add it to my collection and see it on homepage

## Description
![Travel App US2](https://github.com/uwebury/trip-trove/assets/149960642/dd72dc0a-ccaf-42ea-904b-14b381b90841)

## Acceptance criteria
- [x] Homepage contains add button that directs to Create page
- [x] User can enter the destination, start and end date of their trip, add an image URL, enter notes for their trip and a packing list
- [x] User can reset form by clicking on Reset button
- [x] User can save data by clicking on Save button
- [x] If user has not entered any data and clicks on Save button, form validation warning is being displayed

## Tasks
Details page:
- [x] Create form component including handle function
- [x] Use local storage to store new entry
- [x] Create reset button --> resets form (deletes entered content)
- [x] Create Save button --> adds data to locals storage

Form contains the following fields which are validated and additionally two buttons:
- [x] destination (required)
- [x] start date (type date) (required)
- [x] end date (date) (required)
- [x] image URL (string, no picture upload) (not required)
- [x] notes (string, not array) (not required)
- [x] packing list (string, not array) (not required)
- [x] Cancel button (resets form)
- [x] Save (submit) button

Home page:
- [x] Create add button --> directs to create form
- [x] Button "+" on homepage (bottom right, fixed, top layer)

**Comment by CJAkkuec** [comment]
Nice job, just a couple more thoughts:

- I think the second paragraph of the value proposition is not quite necessary.
- The acceptance criteria still need to include the desired behavior of the form e.g. "User can enter the destination of their trip", etc.
