### ISSUE TITLE
US3 - Manual routing

### ISSUE THREAD

**Issue by Aikaakymbaeva** [uwebury/trip-trove#6]
## Value proposition
As a user when I am on the create page
I want to see a toast message when my trip has been saved and I want to be able to reach homepage again
So I know that my entered data has been successfully stored and I can navigate back to homepage

## Description
![Travel App US3](https://github.com/uwebury/trip-trove/assets/149960642/16d51406-0e71-498e-a390-0204748a6263)
## Acceptance criteria

- [x] Back button: Arrow left on create page (bottom left, fixed, top layer)
- [x] Saving data shows alert that data have been saved

## Tasks
- [x] Create BackButton component --> directs back to homepage
- [x] Implement notification feature (toast message)

**Comment by CJAkkuec** [comment]
> As a User when I have added a new trip
> I want to be able to route back to the homepage by clicking the back button
> So I can add multiple new trips uninterrupted.

Strictly speaking, the notification component isn't shown on the wireframe. Perhaps you'd like to add it, still?

**Comment by CJAkkuec** [comment]
> As a User when I am on the homepage
> I want to click an icon
> So I can add a new trip
The value proposition doesn't match the content of the user story.
